name: Users  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /users get lambda deploy zip
        uses: kinlane/mastodon-apievangelist@main
        with:
            args: zip -qq -r m-s-users-g.zip users/get/index.js node_modules
      - name: user get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-users-g
            zip_file: m-s-users-g.zip
      - name: /users post lambda deploy zip
        uses: kinlane/mastodon-apievangelist@main
        with:
            args: zip -qq -r m-s-users-po.zip users/post/index.js node_modules
      - name: user get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-users-po
            zip_file: m-s-users-po.zip
      - name: /users/{user_id} get lambda deploy zip
        uses: kinlane/mastodon-apievangelist@main
        with:
            args: zip -qq -r m-s-users-user-g.zip users/user_id/get/index.js node_modules
      - name: user get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-users-user-g
            zip_file: m-s-users-user-g.zip
      - name: /users/{user_id} put lambda deploy zip
        uses: kinlane/mastodon-apievangelist@main
        with:
            args: zip -qq -r m-s-users-user-pu.zip users/user_id/put/index.js node_modules
      - name: user get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-users-user-pu
            zip_file: m-s-users-user-pu.zip
      - name: /users/{user_id} delete lambda deploy zip
        uses: kinlane/mastodon-apievangelist@main
        with:
            args: zip -qq -r m-s-users-user-d.zip users/user_id/delete/index.js node_modules
      - name: user get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-users-user-d
            zip_file: m-s-users-user-d.zip          
      - name: /users/{user_id}/tags get lambda deploy zip
        uses: kinlane/mastodon-apievangelist@main
        with:
            args: zip -qq -r m-s-users-user-tags-g.zip users/user_id/tags/get/index.js node_modules
      - name: users get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-users-user-tags-g
            zip_file: m-s-users-user-tags-g.zip
      - name: /users/{user_id}/tags post lambda deploy zip
        uses: kinlane/mastodon-apievangelist@main
        with:
            args: zip -qq -r m-s-users-user-tags-po.zip users/user_id/tags/post/index.js node_modules
      - name: users get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-users-user-tags-po
            zip_file: m-s-users-user-tags-po.zip
      - name: /users/bulk get lambda deploy zip
        uses: kinlane/mastodon-apievangelist@main
        with:
            args: zip -qq -r m-s-usersbulk-po.zip users/bulk/post/index.js node_modules
      - name: users get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-usersbulk-po
            zip_file: m-s-usersbulk-po.zip 
      - name: /users/finger get lambda deploy zip
        uses: kinlane/mastodon-apievangelist@main
        with:
            args: zip -qq -r m-s-usersfinger-po.zip users/finger/get/index.js node_modules
      - name: users get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-usersfinger-g
            zip_file: m-s-usersfinger-po.zip              
                      